import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width, height } = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000',
  },
  header: {
    backgroundColor: 'rgb(0, 0, 0)',
    paddingVertical: Platform.OS === 'ios' ? 25 : 20,
    paddingTop: Platform.OS === 'ios' ? 50 : 40,
    top: 0,
    left: 0,
    right: 0,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 40,
    alignItems: 'center',
    position: 'absolute',
    zIndex: 10,
    height: Platform.OS === 'ios' ? 120 : 110,
    justifyContent: 'center',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  headerText: {
    fontSize: Platform.OS === 'ios' ? 28 : 24,
    fontWeight: 'bold',
    color: '#fff',
    textAlign: 'center',
    marginTop: Platform.OS === 'ios' ? 10 : 5,
  },
  backButton: {
    position: 'absolute',
    left: 20,
    top: Platform.OS === 'ios' ? 50 : 40,
    zIndex: 1,
    padding: 5,
  },
  gradient: {
    flex: 1,
    padding: 20,
    paddingTop: Platform.OS === 'ios' ? 120 : 110,
  },
  scrollContainer: {
    paddingBottom: Platform.OS === 'ios' ? 40 : 60,
    flexGrow: 1,
  },
  card: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    minHeight: Platform.OS === 'ios' ? 70 : 65,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  cardLabel: {
    flex: 1,
  },
  cardLabelText: {
    fontSize: Platform.OS === 'ios' ? 18 : 16,
    fontWeight: 'bold',
    color: '#fff',
  },
  cardValueBox: {
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 16,
    minWidth: 80,
    alignItems: 'center',
    minHeight: Platform.OS === 'ios' ? 40 : 38,
    justifyContent: 'center',
  },
  cardValueText: {
    fontSize: Platform.OS === 'ios' ? 16 : 14,
    fontWeight: 'bold',
    color: '#fff',
  },
  actionCard: {
    marginTop: 20,
  },
  advancedButton: {
    backgroundColor: 'rgba(184, 181, 204, 0.6)',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  blurContainer: {
    width: Platform.OS === 'ios' ? '80%' : '85%',
  },
  modalContentGlass: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    width: '100%',
  },
  modalTitle: {
    fontSize: Platform.OS === 'ios' ? 18 : 16,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
    color: '#333',
  },
  modalInput: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: Platform.OS === 'ios' ? 15 : 12,
    width: '100%',
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#ddd',
    fontSize: Platform.OS === 'ios' ? 16 : 15,
    minHeight: Platform.OS === 'ios' ? 50 : 48,
  },
  modalButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: Platform.OS === 'ios' ? 12 : 10,
    paddingHorizontal: 30,
    borderRadius: 10,
    marginBottom: 10,
    width: '100%',
    alignItems: 'center',
    minHeight: Platform.OS === 'ios' ? 50 : 48,
    justifyContent: 'center',
  },
  modalButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: Platform.OS === 'ios' ? 16 : 15,
  },
  modalCancel: {
    color: '#666',
    fontSize: Platform.OS === 'ios' ? 14 : 13,
  },
  // Image Container for Advanced Dev Mode
  imageContainer: {
    marginTop: 40,
    alignItems: 'center',
    marginBottom: 50,
  },
  esp32Image: {
    width: width * 0.6,
    height: 150,
    transform: [{ rotate: '90deg' }],
  },
});