import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
      container: {
    flex: 1,
    },
    gradient: {
        flex: 1,
        paddingTop: 100,
    },
    scrollContainer: {
        padding: 20,
        paddingBottom: 80,
    },
    header: {
        backgroundColor: 'rgb(0, 0, 0)',
        marginBottom: 20,
        paddingVertical: 30,
        top: 0,
        left: 0,
        right: 0,
        borderBottomLeftRadius:40,
        borderBottomRightRadius:40,
        alignItems: 'center',
        position : 'absolute',
        zIndex: 10,
    },
    headerText: {
        marginTop: 10,
        fontSize: 28,
        fontWeight: 'bold',
        color: '#fff',
    },
    chartContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 15,
        padding: 15,
        marginBottom: 15,
    },
    chartTitle: {
        fontSize: 16,
        color: '#fff',
        marginBottom: 10,
        fontWeight: '500',
        textAlign: 'center',
    },
    chart: {
        borderRadius: 15,
    },
    doubleSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 15,
    },
    halfSection: {
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        borderRadius: 15,
        padding: 20,
        width: '48%',
        alignItems: 'center',
    },
    sectionTitle: {
        fontSize: 16,
        color: '#555',
        marginBottom: 5,
        fontWeight: '500',
    },
    valueText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
    },
    configButton: {
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        padding: 16,
        borderRadius: 15,
        alignItems: 'center',
        marginTop: 20,
        marginBottom: 30,
        borderWidth: 2,
        borderColor: '#000',
    },
    configButtonText: {
        color: '#000',
        fontWeight: 'bold',
        fontSize: 18,
    },
    tabContainer: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255, 255, 255, 0.7)',
        borderRadius: 15,
        overflow: 'hidden',
    },
    tab: {
        flex: 1,
        padding: 15,
        alignItems: 'center',
    },
    activeTab: {
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
    },
    tabText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#555',
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 40,
    },
    loadingText: {
        fontSize: 18,
        color: '#fff',
        textAlign: 'center',
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 15,
        padding: 20,
        width: '80%',
    },
    exportButton: {
    backgroundColor: '#3B82F6',
    padding: 15,
    borderRadius: 10,
    margin: 20,
    alignItems: 'center',
    },
    exportButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 14,
    },
    metricSelectorContainer: {
    marginBottom: 15,
    paddingHorizontal: 10,
    },
    metricOption: {
    paddingHorizontal: 15,
    paddingVertical: 8,
    marginRight: 10,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    metricOptionSelected: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    },
    metricOptionText: {
    color: 'white',
    fontSize: 14,
    },
    metricOptionTextSelected: {
    fontWeight: 'bold',
    },
    // container: {
    //     flex: 1,
    //     backgroundColor: '#f5f5f5',
    //     padding: 16,
    // },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 16,
        textAlign: 'center',
    },
    card: {
        backgroundColor: '#fff',
        borderRadius: 8,
        padding: 16,
        marginBottom: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    label: {
        fontSize: 16,
        color: '#555',
        marginBottom: 4,
    },
    value: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#333',
    },
    statusCard: {
        backgroundColor: '#e0f7fa',
        borderRadius: 8,
        padding: 16,
        marginTop: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    statusLabel: {
        fontSize: 16,
        color: '#00796b',
        marginBottom: 4,
    },
    statusValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#004d40',
    },
    errorText: {
        fontSize: 18,
        color: '#d32f2f',
        textAlign: 'center',
        marginTop: 20,
    },
      containerAlt: {
    flex: 1,
    backgroundColor: '#F4C8FF',
  },
  scrollContent: {
    padding: 20,
    paddingBottom: 80,
  },
  titleAlt: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
    alignSelf: 'center',
    backgroundColor: '#000',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    marginBottom: 20,
  },
  itemContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFF0FF',
    borderRadius: 20,
    marginBottom: 20,
    padding: 10,
  },
  labelAlt: {
    fontSize: 16,
    fontWeight: '600',
    paddingHorizontal: 10,
    backgroundColor: '#DCDCDC',
    borderRadius: 20,
  },
  statusBox: {
    paddingVertical: 5,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  statusText: {
    color: '#fff',
    fontWeight: 'bold',
  },

  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 15,
    backgroundColor: '#000',
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  tabItem: {
    color: '#fff',
    fontSize: 14,
  },

});

export default styles;